name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-access-key-id: AKIAS74TMFTXYB3ZA2OF
        aws-secret-access-key: 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
        aws-region: us-east-1
        

    - name: Terraform Init
      #run: terraform init -backend-config="bucket=my-terraform-state-bucket-312025" -backend-config="key=state-file" -backend-config="region=us-east-1" 
      run: terraform init -backend-config="bucket=my-terraform-state-bucket-312025" -backend-config="key=state-file" -backend-config="region=us-east-1"
     
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
